pod_namespace: lighthouse
prowjob_namespace: lighthouse
in_repo_config:
  enabled:
    "*": true
tide:
  queries:
  - labels:
    - approved
    repos:
    - techaid-ci-bot/lighthouse-config
    orgs:
    - techaid-tech
